args:
  models: ["api:Qwen/Qwen2.5-7B-Instruct"]
  datasets: ["CAIL2025"]
  api_url: https://api.siliconflow.cn/v1/chat/completions
  api_key: your_api_key_here
  sub_tasks: ["task1"]
  temperature: 0.6
  top_p: 0.9
  max_tokens: 4096
  batch_size: 8
  repetition_penalty: 1.2
  resume: null