args:
  models: ["/path/to/your/model"]
  datasets: ["JECQA"]
  accelerator: "lmdeploy"
  sub_tasks: ["0_test"]
  num_workers: 8
  tensor_parallel: 1
  temperature: 0.6
  top_p: 0.9
  max_tokens: 4096
  batch_size: 8
  repetition_penalty: 1.2
  resume: null