args:
  models: ["api:Qwen/Qwen3-8B"]
  api_url: https://api.siliconflow.cn/v1/chat/completions
  api_key: sk-ylmpihzxhcjcmralmhgzoxhdzvfbmxkdcelnlcrqqhjisvky
  datasets: ["JECQA"]
  sub_tasks: ["0_test"]
  temperature: 0.6
  top_p: 0.9
  max_tokens: 8192
  batch_size: 8
  repetition_penalty: 1.2
  resume: null