args:
  models: ["/haitao/workspace/model/Qwen2.5-1.5B-Instruct"]
  datasets: ["LawBench"]
  sub_tasks: ["2-1"]
  accelerator: "vllm"
  num_workers: 8
  tensor_parallel: 1
  temperature: 0
  top_p: 0.9
  max_tokens: 16384
  batch_size: 8
  resume: null